package main

import (
	"bufio"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/blugelabs/bluge"
	"github.com/blugelabs/bluge/search"
)

type sourceRecord struct {
	ID          int      `json:"id"`
	URL         string   `json:"url"`
	Title       string   `json:"title"`
	Date        string   `json:"date"`
	Body        string   `json:"body"`
	Summary     string   `json:"summary"`
	Category    string   `json:"category"`
	Tags        []string `json:"tags"`
	ReadingTime int      `json:"readingTime"`
}

// searchResult is the shape the theme's assets/js/search/backends/bluge.js
// renders. These field names are the contract; changing one means changing the
// adapter, and the theme's own reference server in search-server/ alongside it.
type searchResult struct {
	Title       string   `json:"title"`
	Summary     string   `json:"summary"`
	URL         string   `json:"url"`
	Category    string   `json:"category"`
	Tags        []string `json:"tags"`
	Date        string   `json:"date"`
	ReadingTime int      `json:"readingTime"`
}

type searchResponse struct {
	Backend string         `json:"backend"`
	Query   string         `json:"query"`
	Total   uint64         `json:"total"`
	Page    int            `json:"page"`
	Per     int            `json:"per"`
	Offset  int            `json:"offset"`
	Limit   int            `json:"limit"`
	Results []searchResult `json:"results"`
}

// searchParams is one already-parsed query. The grammar is parsed exactly once,
// client-side, in the theme's assets/js/search/query.js; this server receives
// fields and never re-parses `tag:` prefixes or quotes. Repeated fields are
// ANDed, which is what repeating a clause means in the grammar.
type searchParams struct {
	terms      string
	phrases    []string
	categories []string
	tags       []string
	since      time.Time
	until      time.Time
	sinceText  string
	untilText  string
	page       int
	per        int
	offset     int
	sortByDate bool
}

type indexStamp struct {
	SourceSize    int64 `json:"source_size"`
	SourceModUnix int64 `json:"source_mod_unix"`
}

type server struct {
	reader *bluge.Reader
	site   string
}

const (
	defaultPerPage = 20
	maxPerPage     = 100
	maxOffset      = 10_000_000
	dateLayout     = "2006-01-02"
)

func main() {
	var siteDir, sourcePath, indexDir, listen string
	var rebuild, indexOnly bool
	flag.StringVar(&siteDir, "site", "public", "Hugo public directory")
	flag.StringVar(&sourcePath, "source", "server/search-source.jsonl", "JSONL source generated by obsidian2site.py")
	flag.StringVar(&indexDir, "index", "server/bluge-index", "Bluge index directory")
	flag.StringVar(&listen, "listen", "127.0.0.1:8080", "HTTP listen address")
	flag.BoolVar(&rebuild, "reindex", false, "force rebuilding the Bluge index")
	flag.BoolVar(&indexOnly, "index-only", false, "build or validate the Bluge index, then exit")
	flag.Parse()

	if rebuild || indexNeedsBuild(sourcePath, indexDir) {
		log.Printf("building Bluge index from %s", sourcePath)
		if err := buildIndex(sourcePath, indexDir); err != nil {
			log.Fatalf("build search index: %v", err)
		}
	}
	if indexOnly {
		log.Printf("Bluge index ready: %s", indexDir)
		return
	}

	absoluteSite, err := filepath.Abs(siteDir)
	if err != nil {
		log.Fatal(err)
	}
	if info, err := os.Stat(absoluteSite); err != nil || !info.IsDir() {
		log.Fatalf("site directory not found: %s", absoluteSite)
	}

	reader, err := bluge.OpenReader(bluge.DefaultConfig(indexDir))
	if err != nil {
		log.Fatalf("open Bluge index: %v", err)
	}
	defer reader.Close()

	documentCount, err := reader.Count()
	if err != nil {
		log.Fatalf("count Bluge documents: %v", err)
	}
	log.Printf("search backend=bluge documents=%d index=%s", documentCount, indexDir)

	app := &server{reader: reader, site: absoluteSite}
	mux := http.NewServeMux()
	mux.HandleFunc("/api/health", app.health)
	mux.HandleFunc("/api/search", app.search)
	mux.Handle("/", app.staticHandler())

	httpServer := &http.Server{
		Addr:              listen,
		Handler:           securityHeaders(mux),
		ReadHeaderTimeout: 10 * time.Second,
		IdleTimeout:       90 * time.Second,
	}
	log.Printf("serving %s at http://%s", absoluteSite, listen)
	log.Fatal(httpServer.ListenAndServe())
}

func indexNeedsBuild(sourcePath, indexDir string) bool {
	sourceInfo, err := os.Stat(sourcePath)
	if err != nil {
		return true
	}
	raw, err := os.ReadFile(indexDir + ".stamp.json")
	if err != nil {
		return true
	}
	var stamp indexStamp
	if json.Unmarshal(raw, &stamp) != nil {
		return true
	}
	return stamp.SourceSize != sourceInfo.Size() || stamp.SourceModUnix != sourceInfo.ModTime().UnixNano()
}

func buildIndex(sourcePath, indexDir string) error {
	source, err := os.Open(sourcePath)
	if err != nil {
		return err
	}
	defer source.Close()
	info, err := source.Stat()
	if err != nil {
		return err
	}

	temporary := indexDir + ".building"
	if err := os.RemoveAll(temporary); err != nil {
		return err
	}
	writer, err := bluge.OpenWriter(bluge.DefaultConfig(temporary))
	if err != nil {
		return err
	}

	scanner := bufio.NewScanner(source)
	scanner.Buffer(make([]byte, 64*1024), 64*1024*1024)
	batch := bluge.NewBatch()
	batchCount := 0
	total := 0
	flush := func() error {
		if batchCount == 0 {
			return nil
		}
		if err := writer.Batch(batch); err != nil {
			return err
		}
		batch = bluge.NewBatch()
		batchCount = 0
		return nil
	}
	for scanner.Scan() {
		var record sourceRecord
		if err := json.Unmarshal(scanner.Bytes(), &record); err != nil {
			writer.Close()
			return fmt.Errorf("decode source line %d: %w", total+1, err)
		}
		// Term positions on the text fields: a phrase query needs to know which
		// terms are adjacent, and without them `"quoted phrase"` matches nothing
		// while the server looks healthy.
		document := bluge.NewDocument(strconv.Itoa(record.ID)).
			AddField(bluge.NewTextField("title", record.Title).StoreValue().SearchTermPositions()).
			AddField(bluge.NewTextField("body", record.Body).SearchTermPositions()).
			AddField(bluge.NewKeywordField("url", record.URL).StoreValue()).
			AddField(bluge.NewTextField("summary", record.Summary).StoreValue().SearchTermPositions()).
			AddField(bluge.NewKeywordField("date_text", record.Date).StoreValue()).
			AddField(bluge.NewKeywordField("sortdate", record.Date).Sortable()).
			AddField(bluge.NewStoredOnlyField("reading", []byte(strconv.Itoa(record.ReadingTime))))
		if parsed, err := time.Parse(time.RFC3339, record.Date); err == nil {
			document.AddField(bluge.NewDateTimeField("date", parsed))
		}
		// category and tag are keyword fields: the grammar matches them exactly,
		// so they must not be tokenised or stemmed. Stored as well as indexed,
		// because a result card shows them.
		if category := strings.TrimSpace(record.Category); category != "" {
			document.AddField(bluge.NewKeywordField("category", category).StoreValue())
		}
		for _, tag := range record.Tags {
			if tag = strings.TrimSpace(strings.ToLower(tag)); tag != "" {
				document.AddField(bluge.NewKeywordField("tag", tag).StoreValue())
			}
		}
		batch.Update(document.ID(), document)
		batchCount++
		total++
		if batchCount >= 500 {
			if err := flush(); err != nil {
				writer.Close()
				return err
			}
		}
		if total%10000 == 0 {
			log.Printf("indexed %d notes", total)
		}
	}
	if err := scanner.Err(); err != nil {
		writer.Close()
		return err
	}
	if err := flush(); err != nil {
		writer.Close()
		return err
	}
	if err := writer.Close(); err != nil {
		return err
	}
	stamp, _ := json.Marshal(indexStamp{SourceSize: info.Size(), SourceModUnix: info.ModTime().UnixNano()})
	old := indexDir + ".old"
	_ = os.RemoveAll(old)
	if _, err := os.Stat(indexDir); err == nil {
		if err := os.Rename(indexDir, old); err != nil {
			return err
		}
	}
	if err := os.Rename(temporary, indexDir); err != nil {
		_ = os.Rename(old, indexDir)
		return err
	}
	_ = os.RemoveAll(old)
	if err := os.WriteFile(indexDir+".stamp.json", append(stamp, '\n'), 0o644); err != nil {
		return err
	}
	log.Printf("indexed %d notes", total)
	return nil
}

func (s *server) health(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("X-Movenotes-Search-Backend", "bluge")
	count, err := s.reader.Count()
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	writeJSON(w, map[string]any{"backend": "bluge", "notes": count})
	log.Printf("health remote=%s notes=%d", r.RemoteAddr, count)
}

func (s *server) search(w http.ResponseWriter, r *http.Request) {
	started := time.Now()
	w.Header().Set("X-Movenotes-Search-Backend", "bluge")
	if r.Method != http.MethodGet {
		http.Error(w, "GET required", http.StatusMethodNotAllowed)
		return
	}
	params, err := parseParams(r.URL.Query())
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Ask for exactly the window this page needs. Bluge ranks the whole match
	// set but materialises only offset+per documents, which is what keeps
	// response time flat as the archive grows.
	request := bluge.NewTopNSearch(params.per, buildQuery(params)).
		SetFrom(params.offset).
		WithStandardAggregations()
	if params.sortByDate {
		request.SortBy([]string{"-date", "-_score"})
	}
	iterator, err := s.reader.Search(r.Context(), request)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	described := describe(params)
	response := searchResponse{
		Backend: "bluge",
		Query:   described,
		Page:    params.page,
		Per:     params.per,
		Offset:  params.offset,
		Limit:   params.per,
		Results: make([]searchResult, 0, params.per),
	}
	if aggregations := iterator.Aggregations(); aggregations != nil {
		response.Total = aggregations.Count()
	}
	for {
		match, err := iterator.Next()
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		if match == nil {
			break
		}
		result, err := toResult(match)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		response.Results = append(response.Results, result)
	}

	elapsed := time.Since(started)
	w.Header().Set("Server-Timing", fmt.Sprintf("search;dur=%.3f", float64(elapsed.Microseconds())/1000.0))
	writeJSON(w, response)
	log.Printf("search remote=%s query=%q total=%d offset=%d per=%d returned=%d duration=%s",
		r.RemoteAddr, described, response.Total, params.offset, params.per,
		len(response.Results), elapsed.Round(time.Millisecond))
}

// parseParams reads the already-split grammar off the query string. It accepts
// page/per (what the theme's adapter sends) or offset/limit (for anything else),
// and resolves both so the response can report either.
func parseParams(values url.Values) (searchParams, error) {
	params := searchParams{
		terms:      strings.TrimSpace(values.Get("q")),
		phrases:    nonEmpty(values["phrase"]),
		categories: nonEmpty(values["category"]),
		tags:       nonEmpty(values["tag"]),
		sinceText:  strings.TrimSpace(values.Get("since")),
		untilText:  strings.TrimSpace(values.Get("until")),
	}

	for name, raw := range map[string]string{"since": params.sinceText, "until": params.untilText} {
		if raw == "" {
			continue
		}
		parsed, err := time.Parse(dateLayout, raw)
		if err != nil {
			return params, fmt.Errorf("%s: expected YYYY-MM-DD", name)
		}
		if name == "since" {
			params.since = parsed.UTC()
		} else {
			params.until = parsed.UTC()
		}
	}
	if !params.since.IsZero() && !params.until.IsZero() && !params.since.Before(params.until) {
		return params, errors.New("since: must be earlier than until:")
	}

	// `limit` is the alias for `per`; whichever is present wins, and per bounds
	// the response size either way.
	perRaw := values.Get("per")
	if perRaw == "" {
		perRaw = values.Get("limit")
	}
	params.per = boundedInt(perRaw, defaultPerPage, 1, maxPerPage)

	if raw := values.Get("offset"); raw != "" {
		params.offset = boundedInt(raw, 0, 0, maxOffset)
		params.page = params.offset/params.per + 1
	} else {
		params.page = boundedInt(values.Get("page"), 1, 1, 1<<20)
		params.offset = (params.page - 1) * params.per
	}

	// An explicit sort wins; otherwise sort by date exactly when there is no
	// text to rank by, so a filter-only query is in the same order as the first
	// page Hugo server-rendered for that term.
	switch values.Get("sort") {
	case "date":
		params.sortByDate = true
	case "score", "relevance":
		params.sortByDate = false
	default:
		params.sortByDate = params.terms == "" && len(params.phrases) == 0
	}

	return params, nil
}

// buildQuery turns the parsed fields into one Bluge query. Repeated values are
// ANDed; a term matches the title, the summary or the body, with the title
// weighted highest.
func buildQuery(params searchParams) bluge.Query {
	boolean := bluge.NewBooleanQuery()
	clauses := 0

	for _, category := range params.categories {
		boolean.AddMust(bluge.NewTermQuery(category).SetField("category"))
		clauses++
	}
	for _, tag := range params.tags {
		boolean.AddMust(bluge.NewTermQuery(strings.ToLower(tag)).SetField("tag"))
		clauses++
	}
	if params.terms != "" {
		// Every term must appear, in one field or another.
		any := bluge.NewBooleanQuery().SetMinShould(1)
		any.AddShould(
			bluge.NewMatchQuery(params.terms).SetField("title").
				SetOperator(bluge.MatchQueryOperatorAnd).SetBoost(4),
			bluge.NewMatchQuery(params.terms).SetField("summary").
				SetOperator(bluge.MatchQueryOperatorAnd).SetBoost(2),
			bluge.NewMatchQuery(params.terms).SetField("body").
				SetOperator(bluge.MatchQueryOperatorAnd),
		)
		boolean.AddMust(any)
		clauses++
	}
	for _, phrase := range params.phrases {
		any := bluge.NewBooleanQuery().SetMinShould(1)
		any.AddShould(
			bluge.NewMatchPhraseQuery(phrase).SetField("title").SetBoost(4),
			bluge.NewMatchPhraseQuery(phrase).SetField("summary").SetBoost(2),
			bluge.NewMatchPhraseQuery(phrase).SetField("body"),
		)
		boolean.AddMust(any)
		clauses++
	}
	if !params.since.IsZero() || !params.until.IsZero() {
		// since is inclusive and until exclusive, so one day is
		// since:D until:D+1. Dates are indexed as real timestamps, so a note's
		// time of day is compared, not just its calendar date.
		boolean.AddMust(
			bluge.NewDateRangeInclusiveQuery(params.since, params.until, true, false).
				SetField("date"))
		clauses++
	}

	if clauses == 0 {
		return bluge.NewMatchAllQuery()
	}
	return boolean
}

func toResult(match *search.DocumentMatch) (searchResult, error) {
	var result searchResult
	var tags []string
	err := match.VisitStoredFields(func(field string, value []byte) bool {
		switch field {
		case "url":
			result.URL = string(value)
		case "title":
			result.Title = string(value)
		case "summary":
			result.Summary = string(value)
		case "date_text":
			// The contract's `date` is YYYY-MM-DD, which is what a result card
			// renders verbatim. The stored value keeps the note's full RFC 3339
			// timestamp, and the indexed `date` field keeps it for range
			// queries; only the display form is trimmed.
			result.Date = string(value)
			if len(result.Date) > 10 {
				result.Date = result.Date[:10]
			}
		case "category":
			result.Category = string(value)
		case "reading":
			result.ReadingTime, _ = strconv.Atoi(string(value))
		case "tag":
			tags = append(tags, string(value))
		}
		return true
	})
	sort.Strings(tags)
	result.Tags = tags
	if result.Tags == nil {
		result.Tags = []string{}
	}
	return result, err
}

// describe rebuilds the grammar the visitor typed, for the response echo and the
// log line. The client sends fields, so there is no raw query to quote.
func describe(params searchParams) string {
	var parts []string
	for _, category := range params.categories {
		parts = append(parts, clause("category", category))
	}
	for _, tag := range params.tags {
		parts = append(parts, clause("tag", tag))
	}
	if params.sinceText != "" {
		parts = append(parts, "since:"+params.sinceText)
	}
	if params.untilText != "" {
		parts = append(parts, "until:"+params.untilText)
	}
	for _, phrase := range params.phrases {
		parts = append(parts, strconv.Quote(phrase))
	}
	if params.terms != "" {
		parts = append(parts, params.terms)
	}
	return strings.Join(parts, " ")
}

func clause(field, value string) string {
	if strings.ContainsAny(value, " \t\"") {
		return field + ":" + strconv.Quote(value)
	}
	return field + ":" + value
}

func nonEmpty(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		if value = strings.TrimSpace(value); value != "" {
			out = append(out, value)
		}
	}
	return out
}

func boundedInt(raw string, fallback, minimum, maximum int) int {
	value, err := strconv.Atoi(raw)
	if err != nil {
		return fallback
	}
	if value < minimum {
		return minimum
	}
	if value > maximum {
		return maximum
	}
	return value
}

func (s *server) staticHandler() http.Handler {
	files := http.FileServer(http.Dir(s.site))
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.HasPrefix(r.URL.Path, "/api/") {
			http.NotFound(w, r)
			return
		}
		if strings.HasSuffix(r.URL.Path, ".html") || r.URL.Path == "/" {
			w.Header().Set("Cache-Control", "no-cache")
		} else {
			w.Header().Set("Cache-Control", "public, max-age=86400")
		}
		files.ServeHTTP(w, r)
	})
}

func securityHeaders(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.Header().Set("Referrer-Policy", "same-origin")
		next.ServeHTTP(w, r)
	})
}

func writeJSON(w http.ResponseWriter, value any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	encoder := json.NewEncoder(w)
	encoder.SetEscapeHTML(true)
	if err := encoder.Encode(value); err != nil && !errors.Is(err, io.EOF) {
		log.Printf("write JSON: %v", err)
	}
}
