package main

import (
	"bufio"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/blugelabs/bluge"
)

type sourceRecord struct {
	ID      int      `json:"id"`
	URL     string   `json:"url"`
	Title   string   `json:"title"`
	Date    string   `json:"date"`
	Body    string   `json:"body"`
	Summary string   `json:"summary"`
	Tags    []string `json:"tags"`
}

type searchResult struct {
	URL     string `json:"url"`
	Title   string `json:"title"`
	Date    string `json:"date,omitempty"`
	Excerpt string `json:"excerpt,omitempty"`
}

type searchResponse struct {
	Backend string         `json:"backend"`
	Query   string         `json:"query"`
	Total   uint64         `json:"total"`
	Offset  int            `json:"offset"`
	Limit   int            `json:"limit"`
	Results []searchResult `json:"results"`
}

type indexStamp struct {
	SourceSize    int64 `json:"source_size"`
	SourceModUnix int64 `json:"source_mod_unix"`
}

type server struct {
	reader *bluge.Reader
	site   string
}

var operatorRE = regexp.MustCompile(`(?i)^(since|until|tag):(.*)$`)

func main() {
	var siteDir, sourcePath, indexDir, listen string
	var rebuild, indexOnly bool
	flag.StringVar(&siteDir, "site", "public", "Hugo public directory")
	flag.StringVar(&sourcePath, "source", "server/search-source.jsonl", "JSONL source generated by obsidian2site.py")
	flag.StringVar(&indexDir, "index", "server/bluge-index", "Bluge index directory")
	flag.StringVar(&listen, "listen", "127.0.0.1:8080", "HTTP listen address")
	flag.BoolVar(&rebuild, "reindex", false, "force rebuilding the Bluge index")
	flag.BoolVar(&indexOnly, "index-only", false, "build or validate the Bluge index, then exit")
	flag.Parse()

	if rebuild || indexNeedsBuild(sourcePath, indexDir) {
		log.Printf("building Bluge index from %s", sourcePath)
		if err := buildIndex(sourcePath, indexDir); err != nil {
			log.Fatalf("build search index: %v", err)
		}
	}
	if indexOnly {
		log.Printf("Bluge index ready: %s", indexDir)
		return
	}

	absoluteSite, err := filepath.Abs(siteDir)
	if err != nil {
		log.Fatal(err)
	}
	if info, err := os.Stat(absoluteSite); err != nil || !info.IsDir() {
		log.Fatalf("site directory not found: %s", absoluteSite)
	}

	reader, err := bluge.OpenReader(bluge.DefaultConfig(indexDir))
	if err != nil {
		log.Fatalf("open Bluge index: %v", err)
	}
	defer reader.Close()

	documentCount, err := reader.Count()
	if err != nil {
		log.Fatalf("count Bluge documents: %v", err)
	}
	log.Printf("search backend=bluge documents=%d index=%s", documentCount, indexDir)

	app := &server{reader: reader, site: absoluteSite}
	mux := http.NewServeMux()
	mux.HandleFunc("/api/health", app.health)
	mux.HandleFunc("/api/search", app.search)
	mux.Handle("/", app.staticHandler())

	httpServer := &http.Server{
		Addr:              listen,
		Handler:           securityHeaders(mux),
		ReadHeaderTimeout: 10 * time.Second,
		IdleTimeout:       90 * time.Second,
	}
	log.Printf("serving %s at http://%s", absoluteSite, listen)
	log.Fatal(httpServer.ListenAndServe())
}

func indexNeedsBuild(sourcePath, indexDir string) bool {
	sourceInfo, err := os.Stat(sourcePath)
	if err != nil {
		return true
	}
	raw, err := os.ReadFile(indexDir + ".stamp.json")
	if err != nil {
		return true
	}
	var stamp indexStamp
	if json.Unmarshal(raw, &stamp) != nil {
		return true
	}
	return stamp.SourceSize != sourceInfo.Size() || stamp.SourceModUnix != sourceInfo.ModTime().UnixNano()
}

func buildIndex(sourcePath, indexDir string) error {
	source, err := os.Open(sourcePath)
	if err != nil {
		return err
	}
	defer source.Close()
	info, err := source.Stat()
	if err != nil {
		return err
	}

	temporary := indexDir + ".building"
	if err := os.RemoveAll(temporary); err != nil {
		return err
	}
	writer, err := bluge.OpenWriter(bluge.DefaultConfig(temporary))
	if err != nil {
		return err
	}

	scanner := bufio.NewScanner(source)
	scanner.Buffer(make([]byte, 64*1024), 64*1024*1024)
	batch := bluge.NewBatch()
	batchCount := 0
	total := 0
	flush := func() error {
		if batchCount == 0 {
			return nil
		}
		if err := writer.Batch(batch); err != nil {
			return err
		}
		batch = bluge.NewBatch()
		batchCount = 0
		return nil
	}
	for scanner.Scan() {
		var record sourceRecord
		if err := json.Unmarshal(scanner.Bytes(), &record); err != nil {
			writer.Close()
			return fmt.Errorf("decode source line %d: %w", total+1, err)
		}
		document := bluge.NewDocument(strconv.Itoa(record.ID)).
			AddField(bluge.NewTextField("title", record.Title).StoreValue().SearchTermPositions()).
			AddField(bluge.NewTextField("body", record.Body).SearchTermPositions()).
			AddField(bluge.NewKeywordField("url", record.URL).StoreValue()).
			AddField(bluge.NewTextField("summary", record.Summary).StoreValue()).
			AddField(bluge.NewKeywordField("date_text", record.Date).StoreValue())
		if parsed, err := time.Parse(time.RFC3339, record.Date); err == nil {
			document.AddField(bluge.NewDateTimeField("date", parsed))
		}
		for _, tag := range record.Tags {
			if tag = strings.TrimSpace(strings.ToLower(tag)); tag != "" {
				document.AddField(bluge.NewKeywordField("tag", tag))
			}
		}
		batch.Update(document.ID(), document)
		batchCount++
		total++
		if batchCount >= 500 {
			if err := flush(); err != nil {
				writer.Close()
				return err
			}
		}
		if total%10000 == 0 {
			log.Printf("indexed %d notes", total)
		}
	}
	if err := scanner.Err(); err != nil {
		writer.Close()
		return err
	}
	if err := flush(); err != nil {
		writer.Close()
		return err
	}
	if err := writer.Close(); err != nil {
		return err
	}
	stamp, _ := json.Marshal(indexStamp{SourceSize: info.Size(), SourceModUnix: info.ModTime().UnixNano()})
	old := indexDir + ".old"
	_ = os.RemoveAll(old)
	if _, err := os.Stat(indexDir); err == nil {
		if err := os.Rename(indexDir, old); err != nil {
			return err
		}
	}
	if err := os.Rename(temporary, indexDir); err != nil {
		_ = os.Rename(old, indexDir)
		return err
	}
	_ = os.RemoveAll(old)
	if err := os.WriteFile(indexDir+".stamp.json", append(stamp, '\n'), 0o644); err != nil {
		return err
	}
	log.Printf("indexed %d notes", total)
	return nil
}

func (s *server) health(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("X-Movenotes-Search-Backend", "bluge")
	count, err := s.reader.Count()
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	writeJSON(w, map[string]any{"backend": "bluge", "documents": count})
	log.Printf("health remote=%s documents=%d", r.RemoteAddr, count)
}

func (s *server) search(w http.ResponseWriter, r *http.Request) {
	started := time.Now()
	w.Header().Set("X-Movenotes-Search-Backend", "bluge")
	if r.Method != http.MethodGet {
		http.Error(w, "GET required", http.StatusMethodNotAllowed)
		return
	}
	rawQuery := strings.TrimSpace(r.URL.Query().Get("q"))
	if tag := strings.TrimSpace(r.URL.Query().Get("tag")); tag != "" {
		if rawQuery != "" {
			rawQuery += " "
		}
		rawQuery += "tag:" + tag
	}
	limit := boundedInt(r.URL.Query().Get("limit"), 20, 1, 100)
	offset := boundedInt(r.URL.Query().Get("offset"), 0, 0, 1_000_000)
	query, err := parseQuery(rawQuery)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	request := bluge.NewTopNSearch(limit, query).SetFrom(offset).WithStandardAggregations()
	if r.URL.Query().Get("sort") == "date" {
		request.SortBy([]string{"-date", "-_score"})
	}
	iterator, err := s.reader.Search(r.Context(), request)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	response := searchResponse{Backend: "bluge", Query: rawQuery, Offset: offset, Limit: limit, Results: make([]searchResult, 0, limit)}
	if aggregations := iterator.Aggregations(); aggregations != nil {
		response.Total = aggregations.Count()
	}
	for {
		match, err := iterator.Next()
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		if match == nil {
			break
		}
		var result searchResult
		if err := match.VisitStoredFields(func(field string, value []byte) bool {
			switch field {
			case "url":
				result.URL = string(value)
			case "title":
				result.Title = string(value)
			case "date_text":
				result.Date = string(value)
			case "summary":
				result.Excerpt = string(value)
			}
			return true
		}); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		response.Results = append(response.Results, result)
	}
	w.Header().Set("Server-Timing", fmt.Sprintf("search;dur=%.3f", float64(time.Since(started).Microseconds())/1000.0))
	writeJSON(w, response)
	log.Printf("search remote=%s query=%q total=%d offset=%d limit=%d returned=%d duration=%s",
		r.RemoteAddr, rawQuery, response.Total, offset, limit, len(response.Results), time.Since(started).Round(time.Millisecond))
}

func parseQuery(raw string) (bluge.Query, error) {
	tokens, err := splitQuery(raw)
	if err != nil {
		return nil, err
	}
	boolean := bluge.NewBooleanQuery()
	clauses := 0
	var since, until time.Time
	for _, token := range tokens {
		if match := operatorRE.FindStringSubmatch(token.value); match != nil && !token.phrase {
			value := strings.TrimSpace(match[2])
			switch strings.ToLower(match[1]) {
			case "tag":
				if value == "" {
					return nil, errors.New("tag: requires a value")
				}
				boolean.AddMust(bluge.NewTermQuery(strings.ToLower(value)).SetField("tag"))
				clauses++
			case "since", "until":
				date, err := time.Parse("2006-01-02", value)
				if err != nil {
					return nil, fmt.Errorf("%s: expected YYYY-MM-DD", strings.ToLower(match[1]))
				}
				if strings.EqualFold(match[1], "since") {
					since = date.UTC()
				} else {
					until = date.UTC()
				}
			}
			continue
		}
		value := strings.TrimSpace(token.value)
		if value == "" {
			continue
		}
		alternative := bluge.NewBooleanQuery().SetMinShould(1)
		if token.phrase {
			alternative.AddShould(
				bluge.NewMatchPhraseQuery(value).SetField("title").SetBoost(4),
				bluge.NewMatchPhraseQuery(value).SetField("body"),
			)
		} else {
			alternative.AddShould(
				bluge.NewMatchQuery(value).SetField("title").SetOperator(bluge.MatchQueryOperatorAnd).SetBoost(4),
				bluge.NewMatchQuery(value).SetField("body").SetOperator(bluge.MatchQueryOperatorAnd),
			)
		}
		boolean.AddMust(alternative)
		clauses++
	}
	if !since.IsZero() || !until.IsZero() {
		if !since.IsZero() && !until.IsZero() && !since.Before(until) {
			return nil, errors.New("since: must be earlier than until:")
		}
		boolean.AddMust(bluge.NewDateRangeInclusiveQuery(since, until, true, false).SetField("date"))
		clauses++
	}
	if clauses == 0 {
		return bluge.NewMatchAllQuery(), nil
	}
	return boolean, nil
}

type queryToken struct {
	value  string
	phrase bool
}

func splitQuery(raw string) ([]queryToken, error) {
	tokens := make([]queryToken, 0, 8)
	for i := 0; i < len(raw); {
		for i < len(raw) && (raw[i] == ' ' || raw[i] == '\t' || raw[i] == '\n') {
			i++
		}
		if i >= len(raw) {
			break
		}
		if raw[i] == '"' {
			i++
			var builder strings.Builder
			closed := false
			for i < len(raw) {
				if raw[i] == '\\' && i+1 < len(raw) {
					builder.WriteByte(raw[i+1])
					i += 2
					continue
				}
				if raw[i] == '"' {
					i++
					closed = true
					break
				}
				builder.WriteByte(raw[i])
				i++
			}
			if !closed {
				return nil, errors.New("unterminated quoted phrase")
			}
			tokens = append(tokens, queryToken{value: builder.String(), phrase: true})
			continue
		}
		start := i
		for i < len(raw) && raw[i] != ' ' && raw[i] != '\t' && raw[i] != '\n' {
			i++
		}
		tokens = append(tokens, queryToken{value: raw[start:i]})
	}
	return tokens, nil
}

func boundedInt(raw string, fallback, minimum, maximum int) int {
	value, err := strconv.Atoi(raw)
	if err != nil {
		return fallback
	}
	if value < minimum {
		return minimum
	}
	if value > maximum {
		return maximum
	}
	return value
}

func (s *server) staticHandler() http.Handler {
	files := http.FileServer(http.Dir(s.site))
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.HasPrefix(r.URL.Path, "/api/") {
			http.NotFound(w, r)
			return
		}
		if strings.HasSuffix(r.URL.Path, ".html") || r.URL.Path == "/" {
			w.Header().Set("Cache-Control", "no-cache")
		} else {
			w.Header().Set("Cache-Control", "public, max-age=86400")
		}
		files.ServeHTTP(w, r)
	})
}

func securityHeaders(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.Header().Set("Referrer-Policy", "same-origin")
		next.ServeHTTP(w, r)
	})
}

func writeJSON(w http.ResponseWriter, value any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.Header().Set("Cache-Control", "no-store")
	encoder := json.NewEncoder(w)
	encoder.SetEscapeHTML(true)
	if err := encoder.Encode(value); err != nil && !errors.Is(err, io.EOF) {
		log.Printf("write JSON: %v", err)
	}
}
