// Command movenotes-site-server serves a generated movenotes site locally: the
// built Hugo output plus the two search endpoints, from one process.
//
// It is the local half of the pair. The other half is api/, where a serverless
// platform's CDN serves the static files and only /api/* reaches Go code; both
// wrap the same search package, so the two cannot answer differently.
package main

import (
	"flag"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"movenotes/site-server/search"
)

func main() {
	var siteDir, sourcePath, indexDir, listen string
	var rebuild, indexOnly bool
	flag.StringVar(&siteDir, "site", "", "Hugo public directory (default "+search.DefaultSiteDir+")")
	flag.StringVar(&sourcePath, "source", "", "JSONL source generated by obsidian2site.py (default "+search.DefaultSourcePath+")")
	flag.StringVar(&indexDir, "index", "", "Bluge index directory (default "+search.DefaultIndexDir+")")
	flag.StringVar(&listen, "listen", "", "HTTP listen address (default 127.0.0.1:8080, or :$PORT)")
	flag.BoolVar(&rebuild, "reindex", false, "force rebuilding the Bluge index")
	flag.BoolVar(&indexOnly, "index-only", false, "build or validate the Bluge index, then exit")
	flag.Parse()

	service := search.New(search.Config{
		SiteDir:    siteDir,
		SourcePath: sourcePath,
		IndexDir:   indexDir,
	})
	config := service.Config()

	// Indexing happens here and only here. The HTTP handlers never build: it
	// takes minutes on a large archive and needs a writable filesystem.
	if rebuild || search.IndexNeedsBuild(config.SourcePath, config.IndexDir) {
		log.Printf("building Bluge index from %s", config.SourcePath)
		if err := search.BuildIndex(config.SourcePath, config.IndexDir); err != nil {
			log.Fatalf("build search index: %v", err)
		}
	}
	if indexOnly {
		log.Printf("Bluge index ready: %s", config.IndexDir)
		return
	}

	absoluteSite, err := filepath.Abs(config.SiteDir)
	if err != nil {
		log.Fatal(err)
	}
	if info, err := os.Stat(absoluteSite); err != nil || !info.IsDir() {
		log.Fatalf("site directory not found: %s", absoluteSite)
	}

	notes, err := service.Notes()
	if err != nil {
		log.Fatalf("%v", err)
	}
	defer service.Close()
	log.Printf("search backend=bluge notes=%d index=%s", notes, config.IndexDir)

	mux := service.Mux()
	mux.Handle("/", staticHandler(absoluteSite))

	address := listenAddress(listen)
	httpServer := &http.Server{
		Addr:              address,
		Handler:           securityHeaders(mux),
		ReadHeaderTimeout: 10 * time.Second,
		IdleTimeout:       90 * time.Second,
	}
	log.Printf("serving %s at http://%s", absoluteSite, address)
	log.Fatal(httpServer.ListenAndServe())
}

// listenAddress prefers the flag, then $PORT — which is what a container or PaaS
// sets — and finally loopback, so running it by hand does not expose the archive
// to the network by accident.
func listenAddress(listen string) string {
	if listen != "" {
		return listen
	}
	if port := os.Getenv("PORT"); port != "" {
		return ":" + port
	}
	return "127.0.0.1:8080"
}

// staticHandler serves the built site. HTML is revalidated so rebuilding does not
// leave stale note pages in the browser; everything else is fingerprinted or
// immutable enough to cache for a day.
func staticHandler(root string) http.Handler {
	files := http.FileServer(http.Dir(root))
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.HasPrefix(r.URL.Path, "/api/") {
			http.NotFound(w, r)
			return
		}
		if strings.HasSuffix(r.URL.Path, ".html") || r.URL.Path == "/" {
			w.Header().Set("Cache-Control", "no-cache")
		} else {
			w.Header().Set("Cache-Control", "public, max-age=86400")
		}
		files.ServeHTTP(w, r)
	})
}

func securityHeaders(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.Header().Set("Referrer-Policy", "same-origin")
		next.ServeHTTP(w, r)
	})
}
